### ISSUE TITLE
Provide a way to alter the Simple MDE configuration.

### ISSUE THREAD

**Issue by Sander-Toonen** [Raphy/RaphyMarkdownBundle#1]
Out of the box, this bundle works very well. However, at the moment it is quite hard to tweak the MDE editor since no custom options can be passed to the javascript constructor.

I suggest adding an attribute to the MarkdownType called `mde_config` which can contain an array of configuration options. This array can than be passed on as a Json-object to the constructor of the MDE editor.

**Comment by Raphy** [comment]
Hello,

First, thanks for sharing your opinion :)

You are right! The `MarkdownType` must include an option to configure the MDE Javascript constructor.
Do you want to make the PR ?

EDIT : I just have noticed the PR ! Sorry!

**Comment by Raphy** [comment]
@Sander-Toonen : I know it's not the topic, but what do you think about remove the resources `js` and `css` from `markdown_widget.html.twig` to let the developer include where he wants ?

**Comment by Sander-Toonen** [comment]
@Raphy Thank you for merging! Regarding your question: Sounds good to me. When I started using the bundle I was looking for how to include the needed JS, it took me some time to figure out that it was automatically included.

**Comment by Raphy** [comment]
@Sander-Toonen : So, for you, is more intuitive to letting you include the needed resources by your own instead of automatically include them in the widget HTML generation ? I agree. I will fix it a future release ;)
Thanks :)

**Comment by Sander-Toonen** [comment]
@Raphy Indeed, but I'm just speaking for myself.

Other bundles I use take the same approach:
- https://github.com/hearsayit/HearsayRequireJSBundle
- https://github.com/FriendsOfSymfony/FOSJsRoutingBundle
