### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by Sander-Toonen** [Raphy/RaphyMarkdownBundle#6]
Will you update this bundle to support Symfony 4?

**Comment by Raphy** [comment]
Feel free to make a pull request and it will be a pleasure to merge it ;)

Le jeu. 24 mai 2018 18:01, Sander Toonen <notifications@github.com> a
écrit :

**Comment by Sander-Toonen** [comment]
Hmm, no idea why Github isn't able to merge automatically, the changes are quite trivial...

**Comment by Sander-Toonen** [comment]
There it is... :)
